version: 2
project_name: wgo

before:
  hooks:
    - go run ./scripts/release_builtin_func/main.go

builds:
  - id: wgo
    main: ./cmd/wgo
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/wxnacy/wgo/internal/cli.Version={{.Version}}

archives:
  - id: wgo-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^style'
      - '^ci'
      - '^build'
      - '^test'
      - '^Merge pull request'
      - '^Merge branch'
  groups:
    - title: 'Features'
      regexp: '^feat'
    - title: 'Bug Fixes'
      regexp: '^fix'
    - title: 'Performance'
      regexp: '^perf'
    - title: 'Refactor'
      regexp: '^refactor'
    - title: 'Documentation'
      regexp: '^docs'
    - title: 'Build & CI'
      regexp: '^(build|ci)'
    - title: 'Tests'
      regexp: '^test'
    - title: 'Chores'
      regexp: '^chore'

brews:
  - name: wgo
    description: "类 IPython 的 Golang 交互运行工具"
    homepage: "https://github.com/wxnacy/wgo"
    license: "MIT"
    repository:
      owner: wxnacy
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: "wxnacy"
      email: ""
    skip_upload: false
    install: |
      bin.install "wgo"
      # 通过可执行文件生成 bash/zsh/fish/powershell 补全
      generate_completions_from_executable(bin/"wgo", "completion", base_name: "wgo")
    caveats: |
      代码补全依赖 gopls：
        brew install gopls
        或
        go install golang.org/x/tools/gopls@latest

      自动导入/格式化依赖 goimports：
        go install golang.org/x/tools/cmd/goimports@latest

release:
  github:
    owner: wxnacy
    name: wgo
